### ISSUE TITLE
Add continuous integration tests via Travis

### ISSUE THREAD

**Issue by westonruter** [luehrsenheinrich/wp-quicklink#12]
When opening a pull request, the code quality checks including `phpcs` and `eslint` should be run via Travis CI. This will ensure that only code that passes the checks will be merged.

**Comment by westonruter** [comment]
@Luehrsen If you connect the repo with Travis CI I can write the `.travis.yml` file.  To connect the repo, follow [these steps](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci):

1. Go to https://travis-ci.org/ and click “Sign in with GitHub”.
2. Accept the Authorization of Travis CI. You’ll be redirected to GitHub.
3. Click the green Activate button, and click the toggle next to this repo to have it connected with Travis CI.

**Comment by Luehrsen** [comment]
Thanks, I would love to do that myself to learn that, if you don't mind! 👍
