### ISSUE TITLE
Maybe ignore links with get parameters

### ISSUE THREAD

**Issue by Luehrsen** [luehrsenheinrich/wp-quicklink#21]
While reading through a lot of support requests I noticed, that 95% of them happen with preloaded links that have get requests. 

Maybe we should follow what WP Super Cache does and ignore links with get parameters by default?

What do you think, @westonruter?

**Comment by westonruter** [comment]
Yes, that's a good idea. 👍

**Comment by westonruter** [comment]
I assume the main culprit here is the nonce links (via [`wp_nonce_url()`](https://developer.wordpress.org/reference/functions/wp_nonce_url/)).
