### ISSUE TITLE
Supporting Quicklink 2.0

### ISSUE THREAD

**Issue by demianrenzulli** [luehrsenheinrich/wp-quicklink#30]
Hi team!

I'm one of the maintainers of the quicklink library. We wanted to  reach out  to know what the plans for the plugin would be.
First of all, we've recently noticed that [the plugin](https://wordpress.org/plugins/quicklink/) is no longer available. We were wondering if there any plans to make it available again?

We've also noticed that the plugin was using an older version of library. We recently launched Quicklink 2.0 and were wondering if you would be interested to migrate to the new one?

Me and my colleague @westonruter, who has been working on the AMP Wordpress plugin and other CMS efforts so far, would be happy to help on any of these efforts.

cc // @addyosmani, @gilbertococchi, @amedina

**Comment by Luehrsen** [comment]
Hey @demianrenzulli,

we are currently sorting out an issue with our E-Mail infracstructure, that make emails bounce. Thats why the plugins are currently not available.
