### ISSUE TITLE
Rename repo from quicklink to wp-quicklink

### ISSUE THREAD

**Issue by westonruter** [luehrsenheinrich/wp-quicklink#7]
It's easy to confuse this Quicklink plugin repo with the actual Quicklink library repo. Renaming `quicklink` to `wp-quicklink` would help with reducing this confusion.

**Comment by Luehrsen** [comment]
Totally makes sense. 

Will do it in about 12 hours, so make sure the existing dependencies get updated as well.

**Comment by Luehrsen** [comment]
The repository has been renamed to wp-quicklink.
